In [1]:
import pandas as pd
import numpy as np


data = pd.read_csv("E:\ipl_auction\players_list.csv")

<>:5: SyntaxWarning: invalid escape sequence '\i'
<>:5: SyntaxWarning: invalid escape sequence '\i'
C:\Users\ankb2\AppData\Local\Temp\ipykernel_26656\969821021.py:5: SyntaxWarning: invalid escape sequence '\i'
  data = pd.read_csv("E:\ipl_auction\players_list.csv")

In [2]:
data.head()

,List Sr. No.,Set No.,2026\nSet,First Name,Surname,Country,State Association,DOB,Age,Specialism,...,Unnamed: 11,Test caps,ODI caps,T20 caps,IPL,2025\nTeam,2025\nIPL,C/U/A,Reserve Price Rs Lakh,Surname.1
0,1,1,BA1,Devon,Conway,New Zealand,NaN,08/07/1991,34,BATTER,...,NaN,29.0,40.0,62.0,29.0,CSK,6.0,Capped,200,Conway
1,2,1,BA1,Jake,Fraser-McGurk,Australia,NaN,11/04/2002,23,BATTER,...,NaN,NaN,7.0,8.0,15.0,DC,6.0,Capped,200,Fraser-McGurk
2,3,1,BA1,Cameron,Green,Australia,NaN,03/06/1999,26,BATTER,...,RIGHT ARM Fast,33.0,31.0,21.0,29.0,NaN,NaN,Capped,200,Green
3,4,1,BA1,Sarfaraz,Khan,India,MCA,22/10/1997,28,BATTER,...,RIGHT ARM Leg Spin,6.0,NaN,NaN,50.0,NaN,NaN,Capped,75,Khan
4,5,1,BA1,David,Miller,South Africa,NaN,10/06/1989,36,BATTER,...,NaN,NaN,178.0,130.0,141.0,LSG,11.0,Capped,200,Miller

In [6]:
data.columns

Index(['List Sr. No.', 'Set No.', '2026\nSet', 'First Name', 'Surname',
       'Country', 'State Association', 'DOB', 'Age', 'Specialism',
       'Unnamed: 10', 'Unnamed: 11', 'Test caps', 'ODI caps', 'T20 caps',
       'IPL', '2025\nTeam', '2025\nIPL', 'C/U/A', 'Reserve Price Rs Lakh',
       'Surname.1'],
      dtype='object')

In [7]:
data = data.drop('Test caps',axis = 1)

In [8]:
data.head()

,List Sr. No.,Set No.,2026\nSet,First Name,Surname,Country,State Association,DOB,Age,Specialism,Unnamed: 10,Unnamed: 11,ODI caps,T20 caps,IPL,2025\nTeam,2025\nIPL,C/U/A,Reserve Price Rs Lakh,Surname.1
0,1,1,BA1,Devon,Conway,New Zealand,NaN,08/07/1991,34,BATTER,LHB,NaN,40.0,62.0,29.0,CSK,6.0,Capped,200,Conway
1,2,1,BA1,Jake,Fraser-McGurk,Australia,NaN,11/04/2002,23,BATTER,RHB,NaN,7.0,8.0,15.0,DC,6.0,Capped,200,Fraser-McGurk
2,3,1,BA1,Cameron,Green,Australia,NaN,03/06/1999,26,BATTER,RHB,RIGHT ARM Fast,31.0,21.0,29.0,NaN,NaN,Capped,200,Green
3,4,1,BA1,Sarfaraz,Khan,India,MCA,22/10/1997,28,BATTER,RHB,RIGHT ARM Leg Spin,NaN,NaN,50.0,NaN,NaN,Capped,75,Khan
4,5,1,BA1,David,Miller,South Africa,NaN,10/06/1989,36,BATTER,LHB,NaN,178.0,130.0,141.0,LSG,11.0,Capped,200,Miller

In [10]:
columns_to_drop = ['2026\nSet', 'State Association','DOB','Age','Unnamed: 10','Unnamed: 11','ODI caps','T20 caps','IPL','2025\nTeam','2025\nIPL','C/U/A','Surname.1']

for cols in columns_to_drop:
    data = data.drop(cols,axis = 1)

data.head()

,List Sr. No.,Set No.,First Name,Surname,Country,Specialism,Reserve Price Rs Lakh
0,1,1,Devon,Conway,New Zealand,BATTER,200
1,2,1,Jake,Fraser-McGurk,Australia,BATTER,200
2,3,1,Cameron,Green,Australia,BATTER,200
3,4,1,Sarfaraz,Khan,India,BATTER,75
4,5,1,David,Miller,South Africa,BATTER,200

In [11]:
data['Name'] = data['First Name'] + " " + data['Surname']

data.head()

,List Sr. No.,Set No.,First Name,Surname,Country,Specialism,Reserve Price Rs Lakh,Name
0,1,1,Devon,Conway,New Zealand,BATTER,200,Devon Conway
1,2,1,Jake,Fraser-McGurk,Australia,BATTER,200,Jake Fraser-McGurk
2,3,1,Cameron,Green,Australia,BATTER,200,Cameron Green
3,4,1,Sarfaraz,Khan,India,BATTER,75,Sarfaraz Khan
4,5,1,David,Miller,South Africa,BATTER,200,David Miller

In [12]:
data.drop('First Name',axis = 1)
data.drop('Surname', axis = 1)
data.head()

,List Sr. No.,Set No.,First Name,Surname,Country,Specialism,Reserve Price Rs Lakh,Name
0,1,1,Devon,Conway,New Zealand,BATTER,200,Devon Conway
1,2,1,Jake,Fraser-McGurk,Australia,BATTER,200,Jake Fraser-McGurk
2,3,1,Cameron,Green,Australia,BATTER,200,Cameron Green
3,4,1,Sarfaraz,Khan,India,BATTER,75,Sarfaraz Khan
4,5,1,David,Miller,South Africa,BATTER,200,David Miller